# **Python Basics**

## Loops

In [1]:
# 1. For Loop
friends = ["Tayyab", "Zain", "Haseeb"]
print("For Loop output:")
for friend in friends:
    print(f" - {friend}")

# 2. While Loop
count = 0
print("\nWhile Loop output:")
while count < 3:
    print(f" - Count is {count}")
    count += 1

# 3. Nested Loop
print("\nNested Loop output:")
quality = ["Good", "Bad"]
for a in quality:
    for f in friends:
        if f == "Haseeb":
            print(f" - {a} {f}")

For Loop output:
 - Tayyab
 - Zain
 - Haseeb

While Loop output:
 - Count is 0
 - Count is 1
 - Count is 2

Nested Loop output:
 - Good Haseeb
 - Bad Haseeb


## Functions

In [2]:
# 1. Standard Function
def greet(name):
    return f"Hello, {name}!"

print(f"Standard: {greet('Tayyab')}")

# 2. Function with Default Arguments
def power(base, exponent=2):
    return base ** exponent

print(f"Default Args: 5 squared is {power(5)}")

# 3. Lambda Function
double = lambda x: x * 2
print(f"Lambda: Double of 10 is {double(10)}")

# 4. Function with Arbitrary Arguments (*args)
def sum_all(*numbers):
    return sum(numbers)

print(f"*Args: Sum is {sum_all(1, 2, 3, 4)}")

# 5. Function with Arbitrary Keyword Arguments (**kwargs)
def display(**details):
    return details

print(f"**Kwargs: {display(name='Tayyab', age=20)}")

Standard: Hello, Tayyab!
Default Args: 5 squared is 25
Lambda: Double of 10 is 20
*Args: Sum is 10
**Kwargs: {'name': 'Tayyab', 'age': 20}


## Lists

In [4]:
my_list = [10, 20, 30]
print(f"Original list: {my_list}")

# 1. append(): Adds an element at the end
my_list.append(40)
print(f"After append: {my_list}")

# 2. extend(): Add the elements of a list (or any iterable), to the end
my_list.extend([50, 60])
print(f"After extend: {my_list}")

# 3. insert(): Adds an element at the specified position
my_list.insert(1, 15)
print(f"After insert: {my_list}")

# 4. remove(): Removes the first item with the specified value
my_list.remove(15)
print(f"After remove: {my_list}")

# 5. pop(): Removes the element at the specified position
popped = my_list.pop()
print(f"After pop(): {my_list}")

# 6. index(): Returns the index of the first element with the specified value
idx = my_list.index(30)
print(f"Index of 30: {idx}")

# 7. count(): Returns the number of elements with the specified value
my_list.append(20)
count_20 = my_list.count(20)
print(f"Count of 20: {count_20}")

# 8. reverse(): Reverses the order of the list
my_list.reverse()
print(f"After reverse: {my_list}")

# 9. sort(): Sorts the list
my_list.sort()
print(f"After sort: {my_list}")

# 10. copy(): Returns a copy of the list
new_list = my_list.copy()
print(f"Copy of list: {new_list}")

# 11. clear(): Removes all the elements from the list
new_list.clear()
print(f"After clear: {new_list}")

Original list: [10, 20, 30]
After append: [10, 20, 30, 40]
After extend: [10, 20, 30, 40, 50, 60]
After insert: [10, 15, 20, 30, 40, 50, 60]
After remove: [10, 20, 30, 40, 50, 60]
After pop(): [10, 20, 30, 40, 50]
Index of 30: 2
Count of 20: 2
After reverse: [20, 50, 40, 30, 20, 10]
After sort: [10, 20, 20, 30, 40, 50]
Copy of list: [10, 20, 20, 30, 40, 50]
After clear: []


## Dictionaries

In [8]:
# 1. Lists to Dictionary
keys = ["name", "age", "city"]
values = ["Tayyab", 20, "Faisalabad"]

my_dict = dict(zip(keys, values))
print(f"List to Dict: {my_dict}")

# 2. Dictionary to List
list_of_keys = list(my_dict.keys())
list_of_values = list(my_dict.values())
list_of_items = list(my_dict.items())

print(f"\nDict to Keys List: {list_of_keys}")
print(f"Dict to Values List: {list_of_values}")

# 3. Tuples and Dictionaries
print(f"\nDict to List of Tuples: {list_of_items}")

# Creating a dict from tuples
tuple_data = (("Zain", "Haseeb"), ("Good", "Bad"))
dict_from_tuple = dict(tuple_data)
print(f"\nDict from Tuples: {dict_from_tuple}")

List to Dict: {'name': 'Tayyab', 'age': 20, 'city': 'Faisalabad'}

Dict to Keys List: ['name', 'age', 'city']
Dict to Values List: ['Tayyab', 20, 'Faisalabad']

Dict to List of Tuples: [('name', 'Tayyab'), ('age', 20), ('city', 'Faisalabad')]

Dict from Tuples: {'Zain': 'Haseeb', 'Good': 'Bad'}


# **NumPy**

In [10]:
import numpy as np

## Arrays

In [12]:
# 1. Creating 1D Array
arr_1d = np.array([1, 2, 3, 4, 5])
print(f"1D Array: {arr_1d}")

# 2. Creating 2D Array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(f"\n2D Array:\n{arr_2d}")

# 3. Creating array with arange
arr_range = np.arange(0, 10, 2)
print(f"\nArange Array: {arr_range}")

# 4. Creating array of Zeros
arr_zeros = np.zeros((2, 3))
print(f"\nZeros Array:\n{arr_zeros}")

1D Array: [1 2 3 4 5]

2D Array:
[[1 2 3]
 [4 5 6]]

Arange Array: [0 2 4 6 8]

Zeros Array:
[[0. 0. 0.]
 [0. 0. 0.]]


## Vectorized Operations

In [13]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

# Element-wise addition
print(f"Vectorized Add (a + b): {a + b}")

# Element-wise multiplication
print(f"Vectorized Multiply (a * b): {a * b}")

# Conditional vectorization
print(f"Vectorized Condition (a > 15): {a > 15}")

Vectorized Add (a + b): [11 22 33]
Vectorized Multiply (a * b): [10 40 90]
Vectorized Condition (a > 15): [False  True  True]


# **Matrix Operations & Broadcasting**

## Matrix Multiplication

In [14]:
# Define two matrices
A = np.array([[1, 2],
              [3, 4]]) # Shape (2, 2)

B = np.array([[5, 6],
              [7, 8]]) # Shape (2, 2)

# Method 1: using np.dot()
dot_product = np.dot(A, B)
print(f"Matrix Mult (np.dot):\n{dot_product}")

# Method 2: using @ operator (standard for matrix multiplication)
at_product = A @ B
print(f"\nMatrix Mult (@ operator):\n{at_product}")

Matrix Mult (np.dot):
[[19 22]
 [43 50]]

Matrix Mult (@ operator):
[[19 22]
 [43 50]]


## Broadcasting

In [16]:
vector = np.array([1, 2, 3])
scalar_add = vector + 10  # 10 is 'broadcast' to [10, 10, 10]
print(f"\nBroadcasting (Vector + Scalar): {scalar_add}")

# Case 2: Vector and Matrix
matrix = np.array([[1, 1, 1],
                   [1, 1, 1]]) # Shape (2, 3)
row_to_add = np.array([0, 1, 2]) # Shape (3,)

# The row [0, 1, 2] is broadcast across both rows of the matrix
broadcast_result = matrix + row_to_add
print(f"\nBroadcasting (Matrix + Row):\n{broadcast_result}")


Broadcasting (Vector + Scalar): [11 12 13]

Broadcasting (Matrix + Row):
[[1 2 3]
 [1 2 3]]
